### ISSUE TITLE
Move from x86 to AnyCPU

### ISSUE THREAD

**Issue by aloisdg** [delaneyj/three.net#3]
hello,

I try to build the project on VS2013 (W8.1) and I got this warning:

> warning MSB3270: There was a mismatch between the processor architecture of the project being build "MSIL" and the processor architecture of the reference "[internal C# dll]", "x86".

The warning came from the "Pencil.Gaming" lib. It would be nice to move it to AnyCPU. We could see to fix it with @andykorth on the [Pencil.Gaming repository](https://github.com/andykorth/Pencil.Gaming).

If you want to close this warning, you can switch from AnyCPU to x86 in your configuration manager. For further informations see "[How do I fix the Visual Studio compile error, “mismatch between processor architecture”?](http://stackoverflow.com/questions/10113532/how-do-i-fix-the-visual-studio-compile-error-mismatch-between-processor-archit)" on StackOverflow.

**Comment by aloisdg** [comment]
[Pencil.Gaming handles x64 on Windows](https://github.com/andykorth/Pencil.Gaming#glfw3), so does the [nuget package too](https://www.nuget.org/packages/Pencil.Gaming.GLFW3/) (see release note). I think I make a mistake somewhere.

**Comment by delaneyj** [comment]
The NuGet didn't work, happy to move to AnyCPU.  Can you submit a pull?

**Comment by aloisdg** [comment]
The nuget package says that it runs on x64, not that it is in x64. Just realize :)

I can submit a pull when I succeed to run the project.

**Comment by delaneyj** [comment]
Please try now, I just submitted changes to get working on a fresh VS2013 machine.

**Comment by aloisdg** [comment]
> E pur si muove!

It works perfectly.
