### ISSUE TITLE
Add a Coding Style Guides part

### ISSUE THREAD

**Issue by aloisdg** [delaneyj/three.net#4]
Hello,

Which coding style, three.net aims to follow?
- [C# Coding Conventions](https://msdn.microsoft.com/en-us/library/vstudio/ff926074.aspx) by Microsoft
- [Mono Coding Style](http://www.mono-project.com/community/contributing/coding-guidelines/) for the Mono Project

If you want more:
- [NuGet Coding Guidelines](http://docs.nuget.org/contribute/coding-guidelines)
- [MonoGame Coding Guidelines](https://github.com/mono/MonoGame/wiki/Coding-Guidelines)
- [corefx Coding style](https://github.com/dotnet/corefx/wiki/Coding-style)

Some tools who may be useful:
- [StyleCop](http://stylecop.codeplex.com/)
- [Codemaid](http://www.codemaid.net/)
- [Resharper](https://www.jetbrains.com/resharper/)
- [CodeFormatter](https://github.com/dotnet/codeformatter)

**Comment by delaneyj** [comment]
I've had very bad experiences with StyelCop/Resharper over engineering of rules.  The [Microsoft Guide](https://msdn.microsoft.com/en-us/library/vstudio/ff926074.aspx) probably matches the codebase closest for now.  I do prefer using var more often than the guide shows, but I know that its being used for legacy C#.

I'd say go with Microsoft styleguide and if there is a good cross platform tools that can enforce that loosely I'm for it, otherwise its just a review during the pull request.  

thoughts?

**Comment by ns717** [comment]
y've you stop your work on three.net porting project.
its a cool idea.

**Comment by delaneyj** [comment]
Honestly just haven't had the use case I thought I would when I started.  Was looking for more help to bring the project to completetion and add more testing.  Unfortunately it looks like the C# open source world is pretty small at least for 3d stuff.  Lately I've been working on frontend/webgl stuff.  Still <3 C# and think 6+ is a great language for games but just haven't had the interest to go much further.

**Comment by ns717** [comment]
Actually I was working on three.net from last 3-4 days and i found there is no implementation related to animation , morphing , skinning and shader . According to me wt u have done is just create an output window(pensile gaming window) and draw a shape on it. three.js is about animation, morphing and shader . according to me it is just 30-40% code.  
I think it was a great idea you should complete it at-least for animation or morphing.
I love three.js and i am trying to complete your code all your( throws new notImplementedException).

But still it is difficult to understand the whole design and check and identify all incomplete code. and wire them together . 

Please complete morphing animation part at-least if you have some leisure time.

**Comment by delaneyj** [comment]
> According to me wt u have done is just create an output window(pensile gaming window) and draw a shape on it.

That's a gross underestimation of what has gone into the port.  All of the camera, line/point/tri shading, textures, procedural model generation are there.  Most lights and shadow handling is in place.  Some known unimplemented parts are skinning and morph targets (and RTT).  

The reason I didn't do these part yet was I didn't have enough tests in place of the rest of the systems.  As most of the animation happens in the glsl if there are bugs in the shading it only becomes harder to debug when dealing with skinning.  

Of the actual three.js codebase about 85% of it has been ported over; not even close to the 30% your are saying, not sure where you are getting this value from.  If you have the time and desire to complete then please send pull requests as you fill in the gaps.
